server:
  port: 8082

sensor-data:
  topic: ${KAFKA_TOPIC_SENSOR_DATA:sensor-data}

threshold:
  temperature: ${THRESHOLD_TEMPERATURE:35}
  humidity: ${THRESHOLD_HUMIDITY:50}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:central-monitoring}
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.sensordata.central.domain
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.sensordata.central.domain.SensorDataEvent

logging:
  level:
    com.sensordata: INFO
