server:
  port: 8082

sensor-data:
  topic: ${KAFKA_TOPIC_SENSOR_DATA:sensor-data}

threshold:
  temperature: ${THRESHOLD_TEMPERATURE:35}
  humidity: ${THRESHOLD_HUMIDITY:50}

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: central-monitoring
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    com.sensordata: INFO
